#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quiz.Resource", IsApplication=true)]

namespace Quiz
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Quiz.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Quiz.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int ans1_edit = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int ans2_edit = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int ans3_edit = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int ans4_edit = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int answer1 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int answer2 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int answer3 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int answer4 = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int b1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int b2 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int b3 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int b4 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int category_spinner = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int detailed_text = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int done = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int info = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int new_quest = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int quest = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int quest_text = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int question_count_text = 2131099669;
			
			// aapt resource value: 0x7f060004
			public const int question_edit = 2131099652;
			
			// aapt resource value: 0x7f060016
			public const int question_list = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int question_text = 2131099668;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int detailed_question_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main_activity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int new_question_activity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int quest_activity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int question_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int stats_activity = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int add_question = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int ans1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ans2 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ans3 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ans4 = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int info = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int new_question = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int question = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int rightans = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
